version: '3.9'

services:
  monolith-example:
    container_name: monolith-example
    image: hub.timelysoft.org/monolith-example:dev
    restart: always
    ports:
        - '5000:8080'
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
            - ASPNETCORE_ENVIRONMENT=Dev
            - DOTNET_ENVIRONMENT=Dev
    volumes:
            - /home/ubuntu/staticfiles:/app/VirtualDirectory
